#!/bin/sh
set -e

# The following issues won't be fixed in squeeze:
#   - unconditional use of deluser during postrm purge
#   - unconditional use of ucf during postrm purge
# so add these packages to the "fake" essential set.
USED_DURING_PURGE="adduser ucf"

FAILS_TO_REMOVE=


case ${PIUPARTS_OBJECTS%%=*} in
	dpkg)
		# don't install fake essential packages while creating the tarball
		exit 0
		;;
	adduser|ucf)
		# allow testing of the fake essential packages
		exit 0
		;;
	konqueror|konq-plugins|mozart-doc|texlive-full)
		# work around #601961: apt: wrongly thinks install-info is essential
		if [ "$PIUPARTS_DISTRIBUTION" = "squeeze" ]; then
			FAILS_TO_REMOVE="install-info"
		fi
		;;
esac

echo "*** Adding fake essential packages ***"
apt-get install -yf $USED_DURING_PURGE $FAILS_TO_REMOVE
