#!/bin/sh
set -e

# Copyright 2009-2013 Holger Levsen (holger@layer-acht.org)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>

#
#  update piuparts master setup from git (eg. used on pejacevic.debian.org)
#


if [ "`id -n -u`" != "piupartsm" ] ; then
        echo please run this script as piupartsm user
        exit 1
fi

PIUPARTS_PREFIX=/srv/piuparts.debian.org
PIUPARTS_HTDOCS=$PIUPARTS_PREFIX/htdocs
PIUPARTS_TMPDIR=$PIUPARTS_PREFIX/tmp

#
# create $PIUPARTS_PREFIX
#
if [ ! -d $PIUPARTS_PREFIX ] ; then
	sudo mkdir -p $PIUPARTS_PREFIX
	sudo chown piupartsm:piuparts $PIUPARTS_PREFIX
	sudo chmod 0775 $PIUPARTS_PREFIX
fi

#
# update source
#
if [ ! -d $PIUPARTS_PREFIX/src ] ; then
	mkdir -p $PIUPARTS_PREFIX/src
	chmod 0755 $PIUPARTS_PREFIX/src
	cd $PIUPARTS_PREFIX/src
	git clone git://git.debian.org/git/piuparts/piuparts.git
	cd piuparts
	git checkout develop
fi
cd $PIUPARTS_PREFIX/src/piuparts
pwd
# git checkout branch if $1 is given
if [ ! -z "$1" ] ; then
	git checkout $1
fi

# git fetch+pull if $2 is given
if [ ! -z "$2" ] ; then
	git fetch $2
	git pull $2 $1
fi

#
# install everything from GIT into PIUPARTS_PREFIX
#
make clean
make		prefix=$PIUPARTS_PREFIX \
		build-master build-doc
make		prefix=$PIUPARTS_PREFIX \
		docdir=$PIUPARTS_HTDOCS/doc \
		htdocsdir=$PIUPARTS_HTDOCS \
		install-master install-doc install-conf-4-running-from-git
make clean

#
# install copies of the weather icons
# to avoid needing FollowSymlinks in the apache config
#
for icon in weather-severe-alert.png sunny.png
do
	if [ -e /usr/share/icons/Tango/24x24/status/$icon ] ; then
		cp -f /usr/share/icons/Tango/24x24/status/$icon $PIUPARTS_HTDOCS/images/$icon
	fi
done

#
# update $PIUPARTS_PREFIX
#
cd $PIUPARTS_PREFIX
pwd
mkdir -p master backup
# to support multiple hosts with this setup
cd etc/piuparts
HOSTNAME=$(hostname)
for f in piuparts.conf
do
	ln -sf $f.$HOSTNAME $f
done

#
# create working dir
#
mkdir -p $PIUPARTS_TMPDIR
# tell DSA not to back it up
touch $PIUPARTS_TMPDIR/.nobackup

#
# update master home
#
cd
pwd
ln -sf $PIUPARTS_PREFIX/share/piuparts/master bin
crontab $PIUPARTS_PREFIX/etc/piuparts/crontab-master

echo "Update finished."
