#!/bin/sh
set -e

#
#  update piuparts setup on piatti.debian.org
#

# Copyright 2009-2012 Holger Levsen (holger@layer-acht.org)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

if [ "`id -n -u`" != "piupartss" ] ; then
        echo please run this script as piupartss user
        exit 1
fi

PIUPARTS_PREFIX=/org/piuparts.debian.org
PIUPARTS_HTDOCS=$PIUPARTS_PREFIX/htdocs
PIUPARTS_TEMPDIR=$PIUPARTS_PREFIX/tmp

# please cleanup yourself
cd
if [ -d piatti ] ; then
	echo please rm ~/piatti manually
fi

#
# create $PIUPARTS_PREFIX
#
if [ ! -d $PIUPARTS_PREFIX ] ; then
	sudo mkdir -p $PIUPARTS_PREFIX
	sudo chown piupartss:piuparts $PIUPARTS_PREFIX
	sudo chmod 0775 $PIUPARTS_PREFIX
fi

#
# update source
#
if [ ! -d $PIUPARTS_PREFIX/src ] ; then
	mkdir -p $PIUPARTS_PREFIX/src
	chmod 0755 $PIUPARTS_PREFIX/src
	cd $PIUPARTS_PREFIX/src
	git clone git://git.debian.org/git/piuparts/piuparts.git
	cd piuparts
	git checkout develop
fi
cd $PIUPARTS_PREFIX/src/piuparts
pwd
# git checkout branch if $1 is given
if [ ! -z "$1" ] ; then
	git checkout $1
fi

# git fetch+pull if $2 is given
if [ ! -z "$2" ] ; then
	git fetch $2
	git pull $2 $1
fi

#
# install everything from GIT into PIUPARTS_PREFIX
#
make build build-doc
sudo make	prefix=$PIUPARTS_PREFIX \
		docdir=$PIUPARTS_HTDOCS/doc \
		htdocsdir=$PIUPARTS_HTDOCS \
		install install-doc install-conf-4-running-from-git
make clean

#
# update $PIUPARTS_PREFIX
#
cd $PIUPARTS_PREFIX
pwd
mkdir -p master slave backup
sudo chown piupartss:piuparts slave
sudo chown piupartsm:piuparts master htdocs backup
# to support multiple hosts with this setup
HOSTNAME=`hostname`
cd $PIUPARTS_PREFIX/etc/piuparts
pwd
sudo chown piupartss:piuparts . piuparts.conf.*
chmod 0664 piuparts.conf.*
ln -sf piuparts.conf.$HOSTNAME piuparts.conf

#
# create working dir
#
mkdir -p $PIUPARTS_TEMPDIR

#
# update slave home
#
cd
pwd
test ! -L bin || rm bin
test ! -d bin || mv bin bin.old
ln -sf $PIUPARTS_PREFIX/share/piuparts/slave bin
cp $PIUPARTS_PREFIX/etc/piuparts/forward-slave .forward
crontab $PIUPARTS_PREFIX/etc/piuparts/crontab-slave

#
# update master home
#
ssh piupartsm@localhost "
set -e
test ! -L bin || rm bin
test ! -d bin || mv bin bin.old
ln -sf $PIUPARTS_PREFIX/share/piuparts/master bin
cp $PIUPARTS_PREFIX/etc/piuparts/forward-master .forward
crontab $PIUPARTS_PREFIX/etc/piuparts/crontab-master
"

echo "Update finished."
