#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

is_installed()
{
	local pkg="$1"
	dpkg-query -s "$pkg" >/dev/null 2>&1 || return 1
	local status="$(dpkg-query -W -f '${Status}' $pkg)"
	test "$status" != "unknown ok not-installed" || return 1
	test "$status" != "deinstall ok config-files" || return 1
	return 0
}

# Skip while creating the reference chroot.
test "$PIUPARTS_PHASE" != "" || exit 0

if [ "$PIUPARTS_DISTRIBUTION" = "jessie" ]; then

	if [ -h /etc/alternatives/javaws ] && ! is_installed openjdk-7-jre ; then
		#775072 openjdk-7-jre: cleanup broken alternatives left by openjdk-6-jre: javaws, pluginappletviewer
		log_debug
		update-alternatives --remove javaws /usr/lib/jvm/java-6-openjdk/jre/bin/javaws
		update-alternatives --remove pluginappletviewer /usr/lib/jvm/java-6-openjdk/jre/bin/pluginappletviewer
	fi

fi
