#!/bin/sh
set -e

# Copyright 2009 Holger Levsen (holger@layer-acht.org)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

#
# find processes running in deleted chroots
#


PIUPARTS_CONF=${PIUPARTS_CONF:-/etc/piuparts/piuparts.conf}
[ -f "$PIUPARTS_CONF" ] || exit 0

# usage: get_config_value VARIABLE section key [default]
get_config_value()
{
	local section key value
	test -n "$1" && test "$1" = "$(echo "$1" | tr -c -d '[:alnum:]_')" || exit 1
	section="$2"
	key="$3"
	value="$(sed -rn '\#^\['"$section"'\]#,/^\[/ {/^'"$key"'\s*=/ {s/^'"$key"'\s*=\s*//; s/\s*$//; p}}' "$PIUPARTS_CONF")"
	test -n "$value" || value="$4"
	if [ -z "$value" ]; then
		echo "'$key' not set in section [$section] of $PIUPARTS_CONF, exiting." >&2
		exit 1
	fi
	eval "$1"='"$value"'
}

get_config_value SLAVEROOT global slave-directory
get_config_value PIUPARTS_TMPDIR global tmpdir /org/piuparts.debian.org/tmp

STATEFILE=$SLAVEROOT/leftover_processes

# clear the statefile daily and whine again
stamptime=$(stat -c %Z $STATEFILE 2>/dev/null || echo 0)
unixtime=$(date +%s)
difference=$(( $unixtime - $stamptime ))
test $difference -lt 86000 || rm -f $STATEFILE

OUTPUT="$(sudo ls --color=never -lad /proc/*/root 2>/dev/null | grep "$PIUPARTS_TMPDIR" | grep "(deleted)")"
if [ -z "$OUTPUT" ]; then
	rm -f $STATEFILE
elif [ "$(cat $STATEFILE 2>/dev/null)" != "$OUTPUT" ]; then
	echo "Found processes running with a deleted chroot in $PIUPARTS_TMPDIR"
	echo "This is usually because of 'FAIL: Processes are running inside chroot' which usually"
	echo "means the package violates 'must use invoke-rc.d (policy 9.3.3.2)'."
	echo
	echo "$OUTPUT"
	echo
	echo "Please cleanup manually."
	echo "#522918 has been filed to make this manual operation unneeded."
	echo "$OUTPUT" > $STATEFILE
fi
