#!/bin/sh

# Copyright 2009 Holger Levsen (holger@layer-acht.org)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

#
# check for stale mounts and chroots in $PIUPARTS_TMPDIR
#


PIUPARTS_CONF=${PIUPARTS_CONF:-/etc/piuparts/piuparts.conf}
[ -f "$PIUPARTS_CONF" ] || exit 0

# usage: get_config_value VARIABLE section key [default]
get_config_value()
{
	local section key value
	test -n "$1" && test "$1" = "$(echo "$1" | tr -c -d '[:alnum:]_')" || exit 1
	section="$2"
	key="$3"
	value="$(sed -rn '\#^\['"$section"'\]#,/^\[/ {/^'"$key"'\s*=/ {s/^'"$key"'\s*=\s*//; s/\s*$//; p}}' "$PIUPARTS_CONF")"
	test -n "$value" || value="$4"
	if [ -z "$value" ]; then
		echo "'$key' not set in section [$section] of $PIUPARTS_CONF, exiting." >&2
		exit 1
	fi
	eval "$1"='"$value"'
}

get_config_value PIUPARTS_TMPDIR global tmpdir /org/piuparts.debian.org/tmp


MOUNTS="$(mktemp)"
cp /proc/mounts "$MOUNTS"

if [ "$(grep -v trash "$MOUNTS" | grep -c "$PIUPARTS_TMPDIR")" -gt 1 ] ; then
	echo "More than one mountpoint below $PIUPARTS_TMPDIR detected!"
	echo
	grep "$PIUPARTS_TMPDIR" "$MOUNTS"
	echo
	echo "Zero or one mountpoint is normal for piuparts operation, more is not."
	echo "Please investigate and cleanup."
	echo
fi
rm "$MOUNTS"

LS_TMP=$(ls --color=never -l "$PIUPARTS_TMPDIR")
if [ "$(echo "$LS_TMP" | wc -l)" -gt 12 ] ; then
	echo "More than ten directories in $PIUPARTS_TMPDIR detected!"
	echo
	echo "$LS_TMP"
	echo
	echo "$(du -shx "$PIUPARTS_TMPDIR" 2>/dev/null)"
	echo
	echo "One is normal for piuparts operation, more is not."
	echo "Please investigate and cleanup."
	echo
fi

