#!/bin/sh
set -e

# Copyright 2009-2010 Holger Levsen (holger@layer-acht.org)
# Copyright © 2013 Andreas Beckmann (anbe@debian.org)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>

#
# reattach to an existing slave session
#

SESSIONNAME=piuparts_slave_screen

if screen -ls $SESSIONNAME | grep -q "No Sockets found" ; then
  echo "piuparts-slave not running!"
  echo
  echo "ps faxu | grep piuparts"
  ps faxu | grep piuparts
  echo
  echo "screen -ls"
  screen -ls
  exit 1
fi

if [ -w $(tty) ]; then
	screen -x -S $SESSIONNAME
else
	# use script hack to get a new writable tty
	script -q -c "screen -x -S $SESSIONNAME" /dev/null
fi
