#!/bin/sh

# Copyright 2009-2010 Holger Levsen (holger@layer-acht.org)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

#
# reattach to an existing slave session
#
set -e

SCREENLOG=/org/piuparts.debian.org/slave/screenlog.0

if [ $(ps fax|grep piuparts-slave|grep -v grep |wc -l) = 0 ] ; then
  screen -R -S piuparts-slave-screen
else
  echo "$SCREENLOG does not exist, slave not running!"
  echo
  echo "ps faxu | grep piuparts"
  ps faxu | grep piuparts
fi
