#!/bin/sh
set -e

# Copyright 2009-2010 Holger Levsen (holger@layer-acht.org)
# Copyright © 2013 Andreas Beckmann (anbe@debian.org)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

#
# reattach to an existing slave session
#

if [ -z "$1" ] ; then
   SLAVENUM=0
else
   SLAVENUM=$1
fi

if ! `echo $SLAVENUM | grep -E -e "^[0-9]{1}$" >/dev/null` ; then
   echo "slave must be identified as a number between 0 and 9"
   exit
fi

SCREENLOG=/var/lib/piuparts/slave/screenlog.$SLAVENUM

if [ $(ps fax|grep piuparts-slave|grep slave/$SLAVENUM|grep -v grep |wc -l) != 0 ] ; then
  screen -r -S piuparts-slave-screen -p $SLAVENUM -x
else
  echo "piuparts-slave not running!"
  echo
  echo "ps faxu | grep piuparts"
  ps faxu | grep piuparts
  echo
  echo "screen -ls"
  screen -ls
  exit 1
fi

if [ -w $(tty) ]; then
	screen -x -S $SESSIONNAME
else
	# use script hack to get a new writable tty
	script -q -c "screen -x -S $SESSIONNAME" /dev/null
fi
