#!/bin/sh
set -e

# Copyright 2012 Holger Levsen (holger@layer-acht.org)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

#
# cleanup /org/piuparts.debian.org/tmp/
#
# - this should only be run (automatically) on boot
#


PIUPARTS_CONF=${PIUPARTS_CONF:-/etc/piuparts/piuparts.conf}
[ -f "$PIUPARTS_CONF" ] || exit 0

# usage: get_config_value VARIABLE section key [default]
get_config_value()
{
	local section key value
	test -n "$1" && test "$1" = "$(echo "$1" | tr -c -d '[:alnum:]_')" || exit 1
	section="$2"
	key="$3"
	value="$(sed -rn '\#^\['"$section"'\]#,/^\[/ {/^'"$key"'\s*=/ {s/^'"$key"'\s*=\s*//; s/\s*$//; p}}' "$PIUPARTS_CONF")"
	test -n "$value" || value="$4"
	if [ -z "$value" ]; then
		echo "'$key' not set in section [$section] of $PIUPARTS_CONF, exiting." >&2
		exit 1
	fi
	eval "$1"='"$value"'
}

get_config_value PIUPARTS_TMPDIR global tmpdir /org/piuparts.debian.org/tmp


# do nothing if piuparts-slave is running
if pgrep -f share/piuparts/piuparts-slave >/dev/null ; then
	exit 0
fi

# umount all mount points (should be none on boot, but this script can also be called at other times)
for MOUNTPOINT in $(tac /proc/mounts | cut -d " " -f 2 | grep "$PIUPARTS_TMPDIR/")
do
	sudo umount "$MOUNTPOINT"
done

# cleanup tmp
mkdir -p "$PIUPARTS_TMPDIR"
for dir in $(ls -d1 "$PIUPARTS_TMPDIR"/*/ 2>/dev/null || true)
do
	if sudo test -f "$dir/.piuparts.tmpdir"; then
		sudo rm -rf --one-file-system "$dir"
		test ! -d "$dir" || sudo touch "$dir/.piuparts.tmpdir"
	fi
done
