#!/bin/sh

echo "DebugXXX: running $0"
echo "DebugXXX: PIUPARTS_OBJECTS = \"$PIUPARTS_OBJECTS\""
case $PIUPARTS_OBJECTS in 
	sudo) 	echo "DebugXXX: hurray, sudo package being tested"
		export SUDO_FORCE_REMOVE=yes 
		;;
	*)	echo "DebugXXX: hurray, something else tested" ;;
esac

exit 0

apt-get update 
cat /etc/apt/sources.list
dpkg -l tzdata && { 
	apt-get -y --force-yes install libstdc++6
	apt-get upgrade
	apt-get dist-upgrade
}
	
