#!/bin/sh

echo "DebugXXX: running $0 $1"
echo "DebugXXX: PIUPARTS_OBJECTS = $PIUPARTS_OBJECTS"
case $1 in 
	sudo) 	echo "DebugXXX: hurray, sudo package being tested" ;;
	*)	echo "DebugXXX: hurray, something else tested" ;;
esac

exit 0

apt-get update 
cat /etc/apt/sources.list
dpkg -l tzdata && { 
	apt-get -y --force-yes install libstdc++6
	apt-get upgrade
	apt-get dist-upgrade
}
	
