#!/bin/sh

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

echo "Debug: running script $0"
case $PIUPARTS_OBJECTS in 
	apt-listbugs)	log_debug
				# apt-listbugs installs this file which will 
				# make upgrades fail if packages have RC bugs
				rm -f /etc/apt/apt.conf.d/10apt-listbugs 
				;;
esac

exit 0

