#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

echo "Debug: running script $0"

#
# deal with exceptions:
#
case $PIUPARTS_OBJECTS in 
	debconf-english)	log_debug
				# installing debconf-english removed the required
				# package debconf-i18n and piuparts has no way
				# to know this.
				apt-get -y install debconf-i18n
				apt-get clean
				;;
esac

# Allow removal of the kernel running on the host from the chroot.
UNAME_R="$(uname -r)"
echo "linux-image-$UNAME_R linux-image-$UNAME_R/prerm/removing-running-kernel-$UNAME_R boolean false" | debconf-set-selections
