#!/bin/sh

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

echo "Debug: running script $0"
case $PIUPARTS_OBJECTS in 
	apt-listbugs)		log_debug
				# apt-listbugs is run on installations / upgrades 
				# and will them fail if packages have RC bugs
				# (which is good and sensible) 
				echo -e "#/bin/sh\nexit 0" > /usr/sbin/apt-listbugs
				;;
esac

exit 0

