#!/bin/sh

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

echo "Debug: running script $0"

# sudo refuses removal if no root password is set, so set one
# do this unconditionally, as there are quite some packages depending on sudo 
# (and since its harmless and fast)
yes "yes" | passwd 

#
# deal with packages depending on exceptions:
#
case $PIUPARTS_OBJECTS in
	netscript-2.4-upstart)	log_debug
				PIUPARTS_OBJECTS=upstart
				;;
	live-config-upstart)	log_debug
				PIUPARTS_OBJECTS=upstart
				;;
esac

#
# deal with exceptions:
#
case $PIUPARTS_OBJECTS in 
	fai-nfsroot)		log_debug
				# fai-nfsroot refuses installation unless this file exist
				touch /.THIS_IS_THE_FAI_NFSROOT
				;;
	ltsp-client-core)	log_debug
				# ltsp-client-core refuses installation unless this file exist
				touch /etc/ltsp_chroot
				;;
	upstart)		log_debug
				# force installation and removal of essential package sysvinit
				yes 'Yes, do as I say!' | apt-get -y --force-yes install upstart
				;;
	file-rc)		log_debug
				# force installation and removal of essential package sysv-rc
				yes 'Yes, do as I say!' | apt-get -y --force-yes install file-rc
				;;
esac

exit 0

