#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

#
# enable extended purge mode that is available in some packages
# but disabled by default because it might remove valuable user or
# application data
#

case ${PIUPARTS_OBJECTS%%=*} in
	docbookwiki)
		log_debug
		echo "docbookwiki docbookwiki/purge_books boolean true" | debconf-set-selections
		;;
	ifetch-tools)
		log_debug
		echo "ifetch-tools ifetch-tools/purge boolean true" | debconf-set-selections
		;;
	mlmmj)  #668752
		log_debug
		echo "mlmmj mlmmj/remove-on-purge boolean true" | debconf-set-selections
		;;
esac

if [ -d /var/lib/mysql ]; then
	log_debug
	echo "Enabling MySQL database purge."
	echo "mysql-server-5.1 mysql-server-5.1/postrm_remove_databases boolean true" | debconf-set-selections
	echo "mysql-server-5.5 mysql-server-5.5/postrm_remove_databases boolean true" | debconf-set-selections
fi

if [ -d /var/lib/ldap ]; then
	log_debug
	echo "Enabling LDAP database purge."
	echo "slapd slapd/purge_database boolean true" | debconf-set-selections
fi

if [ -d /var/lib/cyrus ] || [ -d /var/spool/cyrus ] || [ -d /var/spool/sieve ]; then
	log_debug
	echo "Enabling Cyrus spool purge."
	echo "cyrus-common cyrus-common/removespools boolean true" | debconf-set-selections
fi

exit 0
