#!/bin/sh
set -e

user=piupartss

if [ "$1" = "purge" ] ; then

    rm -rf /var/lib/piuparts/$user

    if [ -d /var/lib/piuparts/slave ] ; then
        rm -rf /var/lib/piuparts/slave
    fi

    if [ -d /var/lib/piuparts ] ; then
        rmdir /var/lib/piuparts || true
    fi

    if [ -d /etc/piuparts ] ; then
        rmdir /etc/piuparts || true
    fi

    rm -rf /var/cache/piuparts/basetgz/*.log
    rm -rf /var/cache/piuparts/basetgz/*.tar.gz

fi


#DEBHELPER#
