#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

# E: Could not perform immediate configuration on ...
rm -fv /etc/apt/apt.conf.d/piuparts-disable-immediate-configure

if [ "$PIUPARTS_DISTRIBUTION" = "squeeze" ]; then

	case ${PIUPARTS_OBJECTS%%=*} in
		linpopup)
			# package removed after lenny
			log_debug
			for file in /var/lib/linpopup/messages.dat
			do
				test ! -f "$file" || chmod -c o-w "$file"
			done
			;;
	esac

fi

if [ "$PIUPARTS_DISTRIBUTION" = "wheezy" ]; then

	# https://bugs.debian.org/687611
	if [ -f /usr/share/keyrings/debian-archive-removed-keys.gpg~ ]; then
		echo "FIXING /usr/share/keyrings/debian-archive-removed-keys.gpg~"
		mv -v /usr/share/keyrings/debian-archive-removed-keys.gpg~ /usr/share/keyrings/debian-archive-removed-keys.gpg
	fi

	case ${PIUPARTS_OBJECTS%%=*} in
		kismet|\
		tshark|\
		wireshark|\
		wireshark-common|\
		wireshark-dbg|\
		libcap2-bin)
			# libcap2-bin/wheezy is part of the minimal chroot and recommends libpam-cap
			# a conffile moved from libcap2-bin/squeeze to libpam-cap/wheezy
			log_debug
			apt-get install -yf libpam-cap
			;;
		ogre-doc-nonfree)
			# #773059 - ogre-doc: unhandled symlink to directory conversion: /usr/share/doc/PACKAGE
			# package removed after lenny
			log_debug
			apt-get install -yf ogre-1.8-doc
			;;
		phpgacl)
			# #682825
			# package not in wheezy
			log_debug
			for dir in /usr/share/phpgacl/admin/templates_c
			do
				test ! -d "$dir" || chmod -c o-w "$dir"
			done
			;;
	esac

fi

if [ "$PIUPARTS_DISTRIBUTION" = "jessie" ]; then

	# base-files only upgrades pristine /etc/nsswitch.conf
	if ! grep -q ^gshadow: /etc/nsswitch.conf ; then
		echo "Adding gshadow line to /etc/nsswitch.conf"
		sed -i '/^shadow:/a gshadow:        files' /etc/nsswitch.conf
	fi

fi

if [ "$PIUPARTS_DISTRIBUTION" = "stretch" ]; then

	# fakeroot:i386 in jessie shipped these with permissions 0775 (#826318)
	for dir in /usr/share/man/nl /usr/share/man/nl/man1
	do
		test ! -d "$dir" || chmod -c g-w "$dir"
	done

fi
