#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

case ${PIUPARTS_OBJECTS%%=*} in
	file-rc)
		case "$PIUPARTS_DISTRIBUTION" in
			lenny|squeeze*)
				log_debug
				# removal wont work if sysv-rc isn't reinstalled
				yes 'Yes, do as I say!' | apt-get -y --force-yes install sysv-rc
				;;
		esac
		;;
	asclassic)
		case "$PIUPARTS_DISTRIBUTION" in
			lenny)
				# purging works in lenny
				;;
			*)
				log_debug
				# postrm purge unconditionally removes some files that may be gone already
				sed -i 's/rm system.steprc menudefs.hook/rm -f system.steprc menudefs.hook/' /var/lib/dpkg/info/asclassic.postrm
				;;
		esac
		;;
esac
