#!/bin/sh

if [ "$PIUPARTS_DISTRIBUTION" = "lenny" ]; then
	echo "Creating /etc/apt/apt.conf.d/unauthenticated-lenny ..."
	# apt/lenny does not like comments ...
	tee /etc/apt/apt.conf.d/unauthenticated-lenny <<EOF
APT::Get::AllowUnauthenticated "true";
Acquire::Check-Valid-Until "false";
EOF
fi

if [ "$PIUPARTS_DISTRIBUTION" = "squeeze" ] || \
   [ "$PIUPARTS_DISTRIBUTION" = "squeeze-lts" ] || \
   [ "$PIUPARTS_DISTRIBUTION" = "squeeze-backports" ] || \
   [ "$PIUPARTS_DISTRIBUTION" = "squeeze-backports-sloppy" ]; then
	echo "Creating /etc/apt/apt.conf.d/unauthenticated-squeeze ..."
	tee /etc/apt/apt.conf.d/unauthenticated-squeeze <<EOF
# The squeeze signing key has expired.
APT::Get::AllowUnauthenticated "true";
# The Release file is not getting updated.
Acquire::Check-Valid-Until "false";
EOF
fi

if [ "$PIUPARTS_DISTRIBUTION" = "wheezy" ]; then
	echo "Creating /etc/apt/apt.conf.d/unauthenticated-wheezy ..."
	tee /etc/apt/apt.conf.d/unauthenticated-wheezy <<EOF
# The Release file is not getting updated.
Acquire::Check-Valid-Until "false";
EOF
fi

if [ "$PIUPARTS_DISTRIBUTION" = "jessie-backports" ]; then
	echo "Creating /etc/apt/apt.conf.d/unauthenticated-jessie ..."
	tee /etc/apt/apt.conf.d/unauthenticated-jessie <<EOF
# The Release file is not getting updated.
Acquire::Check-Valid-Until "false";
EOF
fi
