#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

case ${PIUPARTS_OBJECTS%%=*} in
	fai-nfsroot)		log_debug
				rm -f /.THIS_IS_THE_FAI_NFSROOT
				;;
	ltsp-client|\
	ltsp-client-core)	log_debug
				rm -f /etc/ltsp_chroot
				;;
	amd64-libs|amd64-libs-dev)
		# leaves a superfluous empty line after purge
		log_debug
		sed -i '3{/^$/d}' /etc/ld.so.conf
		;;
	localepurge)
		case ${PIUPARTS_DISTRIBUTION} in
			lenny*|squeeze*) ;;
			*)
				# reinstall packages where files might have been dropped
				log_debug
				EXTRA=""
				apt-get -u --reinstall --fix-missing install $(dpkg -S LC_MESSAGES 'man/??/man' | cut -d: -f1 | tr ', ' '\n' | sort -u) $EXTRA
				;;
		esac
		;;
esac
