#!/bin/sh
set -e

case ${PIUPARTS_OBJECTS%%=*} in
	TARBALL)
		# skip while creating the tarball
		exit 0
		;;
esac

case $PIUPARTS_DISTRIBUTION in
	lenny|squeeze)
		exit 0
		;;
esac

if [ -d /home ]; then
	echo "Disabling /home"
	mv /home /home.distrib
	if dpkg-divert --help | grep -q -e --no-rename ; then
		dpkg-divert --no-rename /home
	else
		dpkg-divert /home
	fi
	echo "This is a dummy file to prevent creating directories in /home" > /home
	chmod 000 /home
fi
