#!/bin/sh
set -e

test "$PIUPARTS_DISTRIBUTION" = "experimental" || exit 0

# apt-get -t experimental dist-upgrade may pull in too many
# packages that are not co-installable in experimental
# so maintain a list of packages in the sid base system
# that are in experimental, too, and don't cause problems

PKGS=""
PKGS="$PKGS libcomerr2 libss2"
PKGS="$PKGS perl-base"
PKGS="$PKGS libattr1"
PKGS="$PKGS e2fslibs e2fsprogs"
PKGS="$PKGS tzdata"

apt-get -y -t experimental install $PKGS
