#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

case ${PIUPARTS_OBJECTS%%=*} in
	apt-listbugs)		log_debug
				# when installed apt-listbugs is run on installations / upgrades
				# and will cause them to fail due to prompting
				# if packages being installed currently have RC bugs.
				# so disable it here.
				dpkg-divert --rename /usr/sbin/apt-listbugs

				ln -svf /bin/true /usr/sbin/apt-listbugs
				;;
esac
