#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

case $PIUPARTS_OBJECTS in 
	apt-listbugs)		log_debug
				# apt-listbugs is run on installations / upgrades 
				# and will them fail if packages have RC bugs
				# (which is good and sensible) 
				printf "%b\n" "#/bin/sh\nexit 0" > /usr/sbin/apt-listbugs
				;;
esac
