#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

#
# deal with exceptions:
#
case ${PIUPARTS_OBJECTS%%=*} in
	resolvconf)
		log_debug
		echo "Debug: contents of /etc/resolv.conf"
		cat /etc/resolv.conf
		;;
esac
