#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

if [ "$PIUPARTS_DISTRIBUTION" = "wheezy" ]; then

	case ${PIUPARTS_OBJECTS%%=*} in
		libcap2-bin)
			# libcap2-bin/wheezy is part of the minimal chroot and recommends libpam-cap
			# a conffile moved from libcap2-bin/squeeze to libpam-cap/wheezy
			log_debug
			apt-get install -yf libpam-cap
			;;
	esac

fi
