#!/bin/sh
set -e

failed=
for pkg in ${PIUPARTS_OBJECTS%%=*}
do
	# ignore failures for some old packages with many rdepends
	ignore=
	case "${pkg}_${PIUPARTS_DISTRIBUTION}" in
		gij_lenny)			ignore=1 ;;
		gnumeric-common_lenny)		ignore=1 ;;  #554201
		libuim6_lenny)			ignore=1 ;;  #554204
		libuim-data_lenny)		ignore=1 ;;  #554200
		postgresql-8.3-plsh)		ignore=1 ;;
		vlc_lenny)			ignore=1 ;;  #687657
		cdd-common_squeeze)		ignore=1 ;;  #692946
		libcucul0_wheezy)		ignore=1 ;;  # removed
	esac

	# skip check if the package is not installed
	dpkg-query -s "$pkg" >/dev/null 2>&1 || continue
	status="$(dpkg-query -W -f '${Status}' $pkg)"
	test "$status" != "unknown ok not-installed" || continue
	test "$status" != "deinstall ok config-files" || continue

	docdir="/usr/share/doc/$pkg"
	copyright="$docdir/copyright"
	if [ ! -f "$copyright" ]
	then
		if [ -n "$ignore" ]; then
			echo "ignoring failure of $pkg on $PIUPARTS_DISTRIBUTION"
		else
			failed="$failed $copyright"
		fi
		echo "MISSING COPYRIGHT FILE: $copyright"
		echo "# ls -lad $docdir"
		ls -lad "$docdir" || true
		echo "# ls -la $docdir/"
		ls -la "$docdir/" || true
	fi
done

test -z "$failed" || exit 1
