#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

if [ "$PIUPARTS_DISTRIBUTION_NEXT" = "squeeze" ]; then

	case ${PIUPARTS_OBJECTS%%=*} in
		crm114)
				#562946
				log_debug
				echo "crm114 crm114/forceupgrade boolean true" | debconf-set-selections
				;;
	esac

fi

if [ "$PIUPARTS_DISTRIBUTION_NEXT" = "wheezy" ]; then

	# dpkg 1.16 does not like the bad cnews version number cr.g7-40.4
	# cnews was removed after lenny
	case ${PIUPARTS_OBJECTS%%=*} in
		cnews)
				log_debug
				dpkg --purge cnews
				;;
	esac

	# WORKSAROUND #655969: lirc: prompting due to modified conffiles which where not modified by the user: /etc/lirc/hardware.conf
	if [ -f /etc/lirc/hardware.conf ]; then
		log_debug
		sed -i '/^DRIVER=/s/.*/DRIVER="UNCONFIGURED"/' /etc/lirc/hardware.conf
	fi

fi

if [ "$PIUPARTS_DISTRIBUTION_NEXT" = "jessie" ]; then

	case ${PIUPARTS_OBJECTS%%=*} in
		polgen-doc)
			# install-info problems during removal if the package survives
			# polgen-doc was removed after lenny
			log_debug
			dpkg --remove polgen-doc
			;;
	esac

fi
