#!/bin/sh
set -e

test "$PIUPARTS_PHASE" = "install" || exit 0

case "$PIUPARTS_DISTRIBUTION" in
	lenny*|squeeze*|wheezy*) exit 0 ;;
esac

FOREIGN=

case ${PIUPARTS_OBJECTS%%=*} in
	nvidia-driver|\
	nvidia-legacy-*xx-driver|\
	lib*cuda1)
		FOREIGN="i386"
		;;
esac

if [ -n "$FOREIGN" ] && [ "$FOREIGN" != "$(dpkg --print-architecture)" ]; then
	echo "Enabling foreign architecture $FOREIGN for $PIUPARTS_OBJECTS"
	dpkg --add-architecture $FOREIGN
	apt-get update
fi
