#!/bin/sh
set -e

# Skip while creating the reference chroot.
if [ "$PIUPARTS_PHASE" = "" ]; then
	exit 0
fi

CANDIDATES=""
CANDIDATES="$CANDIDATES mysql-server"
CANDIDATES="$CANDIDATES mysql-server-5.5"
CANDIDATES="$CANDIDATES postgresql"
CANDIDATES="$CANDIDATES postgresql-8.4"
CANDIDATES="$CANDIDATES postgresql-9.1"
PACKAGES=""

# early upgrade runs into even more trouble for some packages ...
case ${PIUPARTS_OBJECTS%%=*} in
	med-practice|audiolink)
		CANDIDATES=""
		;;
	redmine)
		CANDIDATES=""
		;;
esac

for pkg in $CANDIDATES
do
	# skip if the package is not installed
	dpkg-query -s "$pkg" >/dev/null 2>&1 || continue
	status="$(dpkg-query -W -f '${Status}' $pkg)"
	test "$status" != "unknown ok not-installed" || continue
	test "$status" != "deinstall ok config-files" || continue

	PACKAGES="$PACKAGES $pkg"
done

if [ -n "$PACKAGES" ]
then
	echo "Upgrading ${PACKAGES# } early"
	apt-get update
	apt-get -y install $PACKAGES
fi
