#!/bin/sh
set -e

# sudo refuses removal if no root password is set, so set one to
# do this unconditionally, as there are quite some packages depending on sudo
# (and since its harmless and fast)
yes "yes" 2>/dev/null | passwd
