#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

#
# deal with exceptions:
#
case ${PIUPARTS_OBJECTS%%=*} in
	isdnlog|isdnutils)
		#WORKSAROUND #431855: fails with "There are still files in /etc/isdn/ that you may want to remove manually."
		if [ "$PIUPARTS_DISTRIBUTION" = "lenny" ]; then
			log_debug
			rm -fv /etc/isdn/*
		fi
		;;
esac

# Allow removal of the kernel running on the host from the chroot.
UNAME_R="$(uname -r)"
echo "linux-image-$UNAME_R linux-image-$UNAME_R/prerm/removing-running-kernel-$UNAME_R boolean false" | debconf-set-selections
