#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts extra for package $PIUPARTS_OBJECTS"
}

#
# these extras are only for the initial package installation
#
if [ "$PIUPARTS_PHASE" != "install" ]; then
	exit 0
fi

case ${PIUPARTS_OBJECTS%%=*} in
	*dkms|\
	ktap|\
	zfs-*|\
	zfsutils-linux)
		# Install kernel headers, so that dkms tries to build a module
		HEADERS=linux-headers
		FLAVOR=unknown
		FLAVOR_i386=686-pae
		case $PIUPARTS_DISTRIBUTION in
			lenny*|squeeze*)
				HEADERS=linux-headers-2.6
				FLAVOR_i386=686
				;;
		esac
		case $(dpkg --print-architecture) in
			amd64)
				FLAVOR=amd64
				;;
			i386)
				FLAVOR=$FLAVOR_i386
				;;
		esac
		case ${PIUPARTS_OBJECTS} in
			*=None)
				# do not test discontinued packages - they won't support newer kernels
				;;
			*)
				log_debug
				apt-get -y install $HEADERS-$FLAVOR
				;;
		esac
		;;
	firmware-ipw2x00)
		log_debug
		echo "firmware-ipw2x00 firmware-ipw2x00/license/accepted boolean true" | debconf-set-selections
		;;
	firmware-ivtv)
		log_debug
		echo "firmware-ivtv firmware-ivtv/license/accepted boolean true" | debconf-set-selections
		;;
	fonts-mathematica)
		log_debug
		echo "fonts-mathematica mathematica-fonts/accept_license boolean true" | debconf-set-selections
		;;
	mathematica-fonts|ttf-mathematica4.1)
		log_debug
		apt-get -y install wget
		echo "mathematica-fonts mathematica-fonts/accept_license boolean true" | debconf-set-selections
		if [ "$PIUPARTS_DISTRIBUTION" = "lenny" ]; then
			echo "ttf-mathematica4.1 ttf-mathematica4.1/accept_license boolean true" | debconf-set-selections
		fi
		;;
esac

if	[ "$PIUPARTS_DISTRIBUTION" = "squeeze" ] || \
	[ "$PIUPARTS_DISTRIBUTION" = "lenny" ]; then

	case ${PIUPARTS_OBJECTS%%=*} in
		*sun-java5-*|*sun-java6-*)
			log_debug
			echo "sun-java6-jre shared/accepted-sun-dlj-v1-1 boolean true" | debconf-set-selections
			;;
		jajuk|\
		liblucene2-java|\
		libworldwind-java|\
		omegat|\
		robocode|\
		solr-common|\
		solr-tomcat5.5|\
		weirdx|\
		weka|\
		worldwind)
			# these packages depend on sun-java* only
			log_debug
			echo "sun-java6-jre shared/accepted-sun-dlj-v1-1 boolean true" | debconf-set-selections
			;;
	esac

fi
