#!/bin/sh
set -e

test "$PIUPARTS_PHASE" = "install" || exit 0

case "$PIUPARTS_DISTRIBUTION" in
	lenny*|squeeze*|wheezy*) exit 0 ;;
esac

FOREIGN=

case ${PIUPARTS_OBJECTS%%=*} in
	nvidia-driver|\
	nvidia-legacy-*xx-driver|\
	lib*cuda1)
		FOREIGN="i386"
		;;
	crossbuild-essential-arm64|\
	*-aarch64-linux-gnu)
		FOREIGN="arm64"
		;;
	crossbuild-essential-armel|\
	*-arm-linux-gnueabi)
		FOREIGN="armel"
		;;
	crossbuild-essential-armhf|\
	*-arm-linux-gnueabihf)
		FOREIGN="armhf"
		;;
	*-mips-linux-gnu)
		FOREIGN="mips"
		;;
	crossbuild-essential-mipsel|\
	*-mipsel-linux-gnu)
		FOREIGN="mipsel"
		;;
	crossbuild-essential-powerpc|\
	*-powerpc-linux-gnu)
		FOREIGN="powerpc"
		;;
	crossbuild-essential-ppc64el|\
	*-powerpc64le-linux-gnu)
		FOREIGN="ppc64el"
		;;
esac

if [ -n "$FOREIGN" ] && [ "$FOREIGN" != "$(dpkg --print-architecture)" ]; then
	echo "Enabling foreign architecture $FOREIGN for $PIUPARTS_OBJECTS"
	dpkg --add-architecture $FOREIGN
	apt-get update
fi
