#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

case ${PIUPARTS_OBJECTS%%=*} in
	file-rc)
		case "$PIUPARTS_DISTRIBUTION" in
			lenny|squeeze*)
				log_debug
				# removal wont work if sysv-rc isn't reinstalled
				yes 'Yes, do as I say!' | apt-get -y --force-yes install sysv-rc
				;;
		esac
		;;
	isdnlog|isdnutils)
		#WORKSAROUND #431855: fails with "There are still files in /etc/isdn/ that you may want to remove manually."
		if [ "$PIUPARTS_DISTRIBUTION" = "lenny" ]; then
			log_debug
			rm -fv /etc/isdn/*
		fi
		;;
	apt-listbugs)
		# cleanup from post_install_exceptions
		log_debug
		rm -f /usr/sbin/apt-listbugs
		dpkg-divert --remove --rename /usr/sbin/apt-listbugs
		;;
	ffgtk|\
	roger-router|\
	roger-router-cli)
		# cleanup from pre_install_exceptions
		log_debug
		dpkg-divert --remove --rename /usr/sbin/lpadmin
		;;
	freedombox-setup)
		log_debug
		# cleanup from pre_install_exceptions
		if [ -e /etc/motd.orig ]; then
			if [ -L /etc/motd ]; then
				rm -v /etc/motd
			fi
			if [ ! -e /etc/motd ]; then
				mv -v /etc/motd.orig /etc/motd
			fi
		fi
		;;
	usrmerge)
		log_debug
		# force removal of usrmerge package
		rm -v /etc/dpkg/dpkg.cfg.d/usrmerge
		;;
esac

# Allow removal of the kernel running on the host from the chroot.
UNAME_R="$(uname -r)"
echo "linux-image-$UNAME_R linux-image-$UNAME_R/prerm/removing-running-kernel-$UNAME_R boolean false" | debconf-set-selections
