#!/bin/sh

[ ! -e /usr/bin/update-alternatives.orig ] && exit 0
rm /usr/bin/update-alternatives
dpkg-divert --rename --remove /usr/bin/update-alternatives
cat /tmp/log-alternatives.log
rm /tmp/log-alternatives.log
