#!/bin/sh
set -e

# If dbconfig-common was already purged, packages that have used
# dbconfig-common in postinst will leave configuration files in
# /etc/dbconfig-common
DBCONFIG="dbconfig-common"

# for purging configuration from /var/lib/systemd/
INITSYSTEMHELPERS="init-system-helpers"

case ${PIUPARTS_DISTRIBUTION} in
	lenny*|squeeze*|wheezy*)
		# package does not exist
		INITSYSTEMHELPERS=""
		;;
esac


case ${PIUPARTS_OBJECTS%%=*} in
	dpkg)
		# skip while creating the tarball
		exit 0
		;;
esac


echo "*** Adding fake essential packages ***"
apt-get install -yf $DBCONFIG $INITSYSTEMHELPERS
