#!/bin/sh
set -e

# If dbconfig-common was already purged, packages that have used
# dbconfig-common in postinst will leave configuration files in
# /etc/dbconfig-common
DBCONFIG="dbconfig-common"

# For purging configuration from /var/lib/systemd/
INITSYSTEMHELPERS="init-system-helpers"

case ${PIUPARTS_DISTRIBUTION} in
	lenny*|squeeze*|wheezy*)
		# package does not exist
		INITSYSTEMHELPERS=""
		;;
esac

# openssl may be used during purge to compute the hash for a
# certificate, otherwise files in /etc/ssl/certs can't be removed.
OPENSSL=""


case ${PIUPARTS_OBJECTS%%=*} in
	dpkg)
		# skip while creating the tarball
		exit 0
		;;
	dbconfig-common|init-system-helpers)
		# allow testing of the fake essential packages
		exit 0
		;;
	stone)
		OPENSSL="openssl"
		;;
esac


echo "*** Adding fake essential packages ***"
apt-get install -yf $DBCONFIG $INITSYSTEMHELPERS $OPENSSL
