#!/bin/sh
set -e

log_debug() {
	echo "Debug: piuparts exception for package $PIUPARTS_OBJECTS"
}

dbconfig_enable_purge()
{
	log_debug
	echo "$1 $1${2+/$2}/dbconfig-remove boolean true" | debconf-set-selections
	echo "$1 $1${2+/$2}/purge boolean true" | debconf-set-selections
}


#
# enable extended purge mode that is available in some packages
# but disabled by default because it might remove valuable user or
# application data
#

case ${PIUPARTS_OBJECTS%%=*} in
	cvsd)
		log_debug
		echo "cvsd cvsd/remove_chroot boolean true" | debconf-set-selections
		;;
	docbookwiki)
		log_debug
		echo "docbookwiki docbookwiki/purge_books boolean true" | debconf-set-selections
		;;
	ifetch-tools)
		log_debug
		echo "ifetch-tools ifetch-tools/purge boolean true" | debconf-set-selections
		;;
	mlmmj)  #668752
		log_debug
		echo "mlmmj mlmmj/remove-on-purge boolean true" | debconf-set-selections
		;;
	movabletype-opensource)
		dbconfig_enable_purge movabletype-opensource
		;;
	nova-common)
		dbconfig_enable_purge nova-common
		;;
	otrs2)
		dbconfig_enable_purge otrs2
		;;
	pdns-backend-sqlite)
		dbconfig_enable_purge pdns-backend-sqlite
		;;
	pdns-backend-sqlite3)
		dbconfig_enable_purge pdns-backend-sqlite3
		;;
	redmine)
		dbconfig_enable_purge redmine instances/default
		;;
	request-tracker3.8)
		dbconfig_enable_purge request-tracker3.8
		;;
	request-tracker4)
		dbconfig_enable_purge request-tracker4
		;;
esac

if [ -d /var/lib/mysql ]; then
	log_debug
	echo "Enabling MySQL database purge."
	echo "mysql-server-5.1 mysql-server-5.1/postrm_remove_databases boolean true" | debconf-set-selections
	echo "mysql-server-5.5 mysql-server-5.5/postrm_remove_databases boolean true" | debconf-set-selections
fi

if [ -d /var/lib/ldap ]; then
	log_debug
	echo "Enabling LDAP database purge."
	echo "slapd slapd/purge_database boolean true" | debconf-set-selections
fi

if [ -d /var/lib/cyrus ] || [ -d /var/spool/cyrus ] || [ -d /var/spool/sieve ]; then
	log_debug
	echo "Enabling Cyrus spool purge."
	echo "cyrus-common cyrus-common/removespools boolean true" | debconf-set-selections
fi

exit 0
